// AUTH TYPES

const SIGN_UP = "SIGN_UP";
const SIGN_IN = "SIGN_IN";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const FETCH_ADDITIONAL_USER_INFO = "FETCH_ADDITIONAL_USER_INFO";
const FETCH_ADDITIONAL_USER_INFO_ERROR = "FETCH_ADDITIONAL_USER_INFO_ERROR";
const SET_AUTH_LOADING = "SET_AUTH_LOADING";
const AUTH_ERROR = "AUTH_ERROR";
const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
const UPDATE_USER_PRFOILE_INFO = "UPDATE_USER_INFO";
const SET_UPDATE_USER_PROFILE_INFO_LOADING =
  "SET_UPDATE_USER_PROFILE_INFO_LOADING";
const UPDATE_USER_PRFOILE_INFO_ERROR = "UPDATE_USER_PRFOILE_INFO_ERROR";
const CLEAR_UPDATE_USER_PRFOILE_INFO_ERROR =
  "CLEAR_UPDATE_USER_PRFOILE_INFO_ERROR";
const SIGN_OUT = "SIGN_OUT";
const SIGN_OUT_ERROR = "SIGN_OUT_ERROR";

// SECURITY CHECKLIST TYPES

const FETCH_SECURITY_CHECKLIST = "FETCH_SECURITY_CHECKLIST";
const SET_FETCH_SECURITY_CHECKLIST_LOADING =
  "SET_FETCH_SECURITY_CHECKLIST_LOADING";
const FETCH_SECURITY_CHECKLIST_ERROR = "FETCH_SECURITY_CHECKLIST_ERROR";
const CLEAR_FETCH_SECURITY_CHECKLIST_ERROR =
  "CLEAR_FETCH_SECURITY_CHECKLIST_ERROR";
const FILTER_SECURITY_CHECKLIST_BY_CLOUD_PROVIDER =
  "FILTER_SECURITY_CHECKLIST_BY_CLOUD_PROVIDER";
const FILTER_SECURITY_CHECKLIST_BY_SERVICE_PROVIDER =
  "FILTER_SECURITY_CHECKLIST_BY_SERVICE_PROVIDER";
const CLEAR_SECURITY_CHECKLIST_FILTERS = "CLEAR_SECURITY_CHECKLIST_FILTERS";
const UPDATE_SECURITY_CHECKLIST = "UPDATE_SECURITY_CHECKLIST";
const SET_UPDATE_SECURITY_CHECKLIST_LOADING =
  "SET_UPDATE_SECURITY_CHECKLIST_LOADING";
const UPDATE_SECURITY_CHECKLIST_ERROR = "UPDATE_SECURITY_CHECKLIST_ERROR";
const CLEAR_UPDATE_SECURITY_CHECKLIST_ERROR =
  "CLEAR_UPDATE_SECURITY_CHECKLIST_ERROR";

export {
  SIGN_UP,
  SIGN_IN,
  SET_CURRENT_USER,
  FETCH_ADDITIONAL_USER_INFO,
  FETCH_ADDITIONAL_USER_INFO_ERROR,
  SET_AUTH_LOADING,
  AUTH_ERROR,
  CLEAR_AUTH_ERROR,
  UPDATE_USER_PRFOILE_INFO,
  SET_UPDATE_USER_PROFILE_INFO_LOADING,
  UPDATE_USER_PRFOILE_INFO_ERROR,
  CLEAR_UPDATE_USER_PRFOILE_INFO_ERROR,
  SIGN_OUT,
  SIGN_OUT_ERROR,
  FETCH_SECURITY_CHECKLIST,
  SET_FETCH_SECURITY_CHECKLIST_LOADING,
  FETCH_SECURITY_CHECKLIST_ERROR,
  CLEAR_FETCH_SECURITY_CHECKLIST_ERROR,
  FILTER_SECURITY_CHECKLIST_BY_CLOUD_PROVIDER,
  FILTER_SECURITY_CHECKLIST_BY_SERVICE_PROVIDER,
  CLEAR_SECURITY_CHECKLIST_FILTERS,
  UPDATE_SECURITY_CHECKLIST,
  SET_UPDATE_SECURITY_CHECKLIST_LOADING,
  UPDATE_SECURITY_CHECKLIST_ERROR,
  CLEAR_UPDATE_SECURITY_CHECKLIST_ERROR,
};
